### ISSUE TITLE
Map documentation

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/GTPSA.jl#45]
Documentation needed:
- [ ] How to setup a map including how to set the maximum order differently for different independent variables.
- [ ] List of map functions (inverse, concatenation, etc.)

**Comment by mattsignorelli** [comment]
Maps would just be vectors of TPSAs in Julia, and setting the orders differently for the variables is shown in the last Descriptor constructor of the GTPSA Structs tab of the documentation. Though this isn't the most clear so I'm thinking about how to better structure the documentation and will include examples for these. Working on map functions in Julia now

**Comment by mattsignorelli** [comment]
I added a section to definitions clarifying what a "GTPSA map" is and how it isn't a DA map. The rest will be taken care of in the analysis package. The map functions are shown in the TPS and Map Methods section.
