### ISSUE TITLE
Unit TPS constructor needed

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/GTPSA.jl#50]
Instead of constructing unit TPS variables one at a time, it would be convenient to be able to create an array at once.  Something like:
`x = unit_maps(descriptor)`
So that `x[1]`, `x[2]`, ..., `x[N]` are unit maps for variables 1, 2, ..., N. With this, a TPS can be constructed like:
`y = 2 + 4.3*x[1]^2 + x[3]`

**Comment by mattsignorelli** [comment]
This has been implemented in `vars`, `params`, `complexvars`, and `complexparams`.
