### ISSUE TITLE
vars(d) throws error

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/GTPSA.jl#90]
The documentation says that vars() should work but it does not:
```
julia> x = vars()
ERROR: MethodError: no method matching vars()
```
But `x = vars(::Descriptor)` does work

**Comment by mattsignorelli** [comment]
I am not seeing this bug on the current stable release (v0.2.1) or the most recent dev version

**Comment by DavidSagan** [comment]
Sorry I did not update properly. Now `var()` works but:
```
julia> x = vars(d)
ERROR: MethodError: no method matching vars(::Descriptor)
```
Should this not work?

**Comment by DavidSagan** [comment]
Also what is the status of the default descriptor?

**Comment by mattsignorelli** [comment]
Yes, this is a new change. For consistency with the rest of the constructors `TPS`/`ComplexTPS`, it is now a kwarg `use` so

```
x = vars(use=d)
```

`use` could also be a `TPS` or `ComplexTPS`. Tomorrow I will push a new stable release with docs updated and many bug fixes I found

**Comment by DavidSagan** [comment]
OK I wait.

**Comment by mattsignorelli** [comment]
I also found a C bug in `cutord` that leads to silent memory corruption, this was reported upstream to Laurent but my push tomorrow has a barrier to prevent this from happening.

There is a global `GTPSA.desc_current` that is set every time the user creates a new `Descriptor`, but could also be set manually. This I believe is documented

**Comment by mattsignorelli** [comment]
v0.2.2 incoming now...
