### ISSUE TITLE
Test inversion time with parameters

### ISSUE THREAD

**Issue by DavidSagan** [bmad-sim/GTPSA.jl#98]
Take the case, for example, of 2 variables at order 5 and 100 knobs at order 1 versus 102 variables with the first two at order 5 and the others at order 1. Does the map inversion time differ between the two cases?

**Comment by mattsignorelli** [comment]
Inversion will definitely differ for this test, because one is a 2x2 matrix and the other is a 102x102 matrix (with how mad_tpsa handles the inversion)

**Comment by DavidSagan** [comment]
But what is the time difference?

**Comment by mattsignorelli** [comment]
Laurent in his email implemented this in the C code and found negligible differences in time
